language:  python
env:
  - TOXENV=cov
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
      services:
      - docker
    - python: 3.3
      env:
      - TOXENV=py33
      services:
      - docker
    - python: 3.4
      env:
      - TOXENV=py34
      services:
      - docker
    - python: 3.5
      env:
      - TOXENV=py35
      services:
      - docker
    - python: 3.6
      env:
      - TOXENV=py36
      services:
      - docker
    - python: pypy
      env:
      - TOXENV=pypy
      services:
      - docker
  allow_failures:
    - env: TOXENV=cov
install:
   - pip install tox
script:
  - tox
  - if [ $TOXENV != "cov" ];
    then
      echo 'Start Integration-Tests in Docker:';
      python tests/integration_test_runner.py `echo ${PWD}` $TOXENV dpkg pacman rpm;
    fi
after_script:
  - if [ $TOXENV == "cov" ];
    then
      pip install coveralls;
      coveralls;
    fi