language:  python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=cov
matrix:
  allow_failures:
    - env: TOXENV=cov
install: 
   - pip install --quiet --use-mirrors tox
script:
   - tox
after_script:
  - if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
    fi
  - echo 'Start Integration-Tests in Docker:'
  - echo ${PWD}
  - python tests/IntegrationTestRunner.py echo ${PWD} dpkg